server:
  port: 8180
  servlet:
    context-path: /ycx
  tomcat:
    uri-encoding: utf-8

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: memorpro
  datasource:
      url: jdbc:mysql://localhost:3306/memorpro
      username: root
      password: 0313..Ycx
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource