spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update #自动根据实体类创建表
    show-sql: false
  application:
    name: ycx

#解决metrics 401的问题
management:
  security:
    enabled: false

# http的header头的大小扩展至2MB
server:
  max-http-header-size: 2097152